name = "backpow-mcp"
main = "src/index.ts"
compatibility_date = "2026-09-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "mcp.backpow.com", custom_domain = true }
]

[observability]
enabled = true
head_sampling_rate = 1
